-- PROCEDURE - 17/04/25

-- CRIANDO UMA TABELA PRA FAZER A PROCEDURE
CREATE TABLE DEPT (DEPTNO NUMBER(5) PRIMARY KEY, 
DNAME VARCHAR2 (20)
);
CREATE TABLE EMP (EMPNO NUMBER(6) PRIMARY KEY,
ENAME VARCHAR (15),
SALARIO NUMBER(10,2),
DEPTNO NUMBER(5) REFERENCES DEPT
);

INSERT INTO DEPT VALUES(1,'CONTABILIDADE');

INSERT INTO DEPT VALUES(2,'TI');

INSERT INTO DEPT VALUES(3,'VENDAS');

INSERT INTO EMP VALUES(100,'JOSE',2000,1);

INSERT INTO EMP VALUES(101,'JULIO',4000,1);

INSERT INTO EMP VALUES(102,'CARLOS',3000,2);

INSERT INTO EMP VALUES(103,'LUIS',1200,2);

INSERT INTO EMP VALUES(104,'MARIA',5000,2);

INSERT INTO EMP VALUES(105,'LUZIA',4500,3);

-- FAZENDO UM INVOCADOR DE PROCEDURE DO CODIGO ACIMA NO MODO 'IN'
declare
 vsal number(9,2);
 vperc number(5,2):=&percentual;
 begin
 SELECT SALARIO INTO vsal FROM EMP WHERE EMPNO=&funcionario;
 calcula(vsal,vperc);
 EXCEPTION
 when NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('INEXISTTENTE REGISTRO');
 end;
 /

-- USANDO INVOCADOR DE PROCEDURE COM 'OUT'
 SET SERVEROUTPUT ON
 declare
 vsal number(9,2);
 vperc number(5,2):=11;
 VRESULTADO NUMBER:=2000;
 begin
 SELECT SALARIO INTO vsal FROM EMP WHERE EMPNO=&funcionario;
 calcula_OUT(vsal,vperc,VRESULTADO);
 EXCEPTION
 when NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE('INEXISTENTE REGISTRO');
 end;

-- FAZENDO INVOCADOR NO MODO IN OUT
DECLARE
VSAL NUMBER (9,2);
VPERC NUMBER(5,2) :=11;
VRESULT NUMBER(6,2) := 2000;
BEGIN
    SELECT SALARIO INTO VSAL WHERE EMPNO=&FUNCIONARIO;
    CALCULA_IN_OUT(VALL, VPERC, VRESULT);
END;


-----------------------------------------------------------------

-- faz a aparicação da conta CALCULA
SET SERVEROUTPUT ON 

-- usando CALCULA IN em procedure 
CREATE OR REPLACE PROCEDURE CALCULA(
    VALOR1 IN NUMBER,
    VALOR2 NUMBER
) IS VRESULT NUMBER;
BEGIN
    VRESULT := VALOR1*VALOR2/100;
    DBMS_OUTPUT.PUT_LINE('o RESULTADO É : ' || VRESULT);
END CALCULA;
/
--  executa a calcula e colocar os dois valor ja
-- variaveis de subtituição, que são criadas em tempo de execução
EXECUTE CALCULA(100,10);


-- CALCULA OUT 
CREATE OR REPLACE PROCEDURE CALCULA_OUT(
    VCALOR1 IN NUMBER, VALOR2 NUMBER, VRESULT OUT NUMBER
) IS
BEGIN
    VRESULT := VALOR1 * VALOR2 /100+VRESULT;
    DBMS_OUTPUT.PUT_LINE('O resultado é : ' || VRESULT);
END CALCULA_OUT;
/
-- SAIDA DA EXECUÇÃO CALCULA_OUT



-- USANDO CALCULA IN OUT 
create or replace procedure CALCULA_IN_OUT
 (VALOR1 IN NUMBER,VALOR2 NUMBER, VRESULT IN OUT NUMBER) IS
 BEGIN
 VRESULT := VALOR1*VALOR2/100+VRESULT;
 DBMS_OUTPUT.PUT_LINE(' O RESULTADO É:' || VRESULT);
 END CALCULA_IN_OUT;
 